
import java.awt.Graphics;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis
 */

public class grafun extends javax.swing.JFrame {
    private int maxX,maxY,mx,my;
    private double escX,escY,x,y;
    
    public grafun() {
        initComponents();
        maxX=this.jPanel1.getWidth();
        maxY=this.jPanel1.getHeight();
        mx=maxX/2;
        my=maxY/2;
        escX=escY=10;
    }
    
    @Override
    public void paint(Graphics g){
        
        this.paintComponents(g);
        segmento(-50, 0, 50, 0);
        segmento(0, -50, 0, 50);
        coordenada(x,y);
 
              
    }
    
    public void segmento(double x1, double y1, double x2, double y2){
        jPanel1.getGraphics().drawLine((int)(mx+escX*x1), (int)(mx-escY*y1), (int)(mx+escX*x2), (int)(mx-escY*y2));
    }
    
    public void coordenada(double x, double y){
        jPanel1.getGraphics().drawOval((int)(mx+escX*x), (int)(mx-escY*y), 1, 1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPoli = new javax.swing.JButton();
        jButtonRac = new javax.swing.JButton();
        jButtonExp = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jButtonTrig = new javax.swing.JButton();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Escala = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPoli.setText("Polinomial");
        jButtonPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoliActionPerformed(evt);
            }
        });

        jButtonRac.setText("Racional");
        jButtonRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRacActionPerformed(evt);
            }
        });

        jButtonExp.setText("Exponencial");
        jButtonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpActionPerformed(evt);
            }
        });

        jButtonLog.setText("Logarítmica");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        jButtonTrig.setText("Trigronométrica");
        jButtonTrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrigActionPerformed(evt);
            }
        });

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        jLabel2.setText("a");

        jLabel3.setText("b");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setName("PanelR2"); // NOI18N

        Escala.setValue(5);
        Escala.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EscalaStateChanged(evt);
            }
        });

        jLabel1.setText("Escala");

        jButton2.setText("Borrar lienzo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPoli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTrig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(a)
                                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Escala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPoli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTrig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Escala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("PanelR2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void EscalaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EscalaStateChanged
        // TODO add your handling code here:
        escX=escY=(int)(this.Escala.getValue());
        repaint();
    }//GEN-LAST:event_EscalaStateChanged

    private void jButtonPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPoliActionPerformed
        double min, max, x0, x1, fx0, fx1;
        try{
         min = Integer.parseInt(a.getText());
         max = Integer.parseInt(b.getText());   
        }
        catch(RuntimeException ex){
           JOptionPane.showMessageDialog(this,
                   "INTRODUCIR EL INTERVALO [a,b]",
                   "ERROR", JOptionPane.ERROR_MESSAGE);
           return;
        } 
        
        for(int i=0; i<100; i++){
                x0 = min + i*(max-min)/100;
                fx0 = x0*x0*x0-2*x0*x0-3*x0;
                x1 = min + (i+1)*(max-min)/100;
                fx1 = x1*x1*x1-2*x1*x1-3*x1;
                segmento(x0,fx0,x1,fx1);
            }
    }//GEN-LAST:event_jButtonPoliActionPerformed

    private void jButtonRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRacActionPerformed
        double min, max, x0, x1, fx0, fx1;
        try{
         min = Integer.parseInt(a.getText());
         max = Integer.parseInt(b.getText());   
        }
        catch(RuntimeException ex){
           JOptionPane.showMessageDialog(this,
                   "INTRODUCIR EL INTERVALO [a,b]",
                   "ERROR", JOptionPane.ERROR_MESSAGE);
           return;
        }  
        
        if(min<3.0 && max>3.0){
           for(int i=0; i<100; i++){
                x0 = min + i*(2.99-min)/100;
                fx0 = (x0*x0+x0-13.0)/(x0-3);
                x1 = min + (i+1)*(2.99-min)/100;
                fx1 = (x1*x1+x1-13.0)/(x1-3);
                segmento(x0,fx0,x1,fx1);
            }
        
           for(int i=0; i<100; i++){
                x0 = 3.01 + i*(max-3.01)/100;
                fx0 = (x0*x0+x0-13.0)/(x0-3);
                x1 = 3.01 + (i+1)*(max-3.01)/100;
                fx1 = (x1*x1+x1-13.0)/(x1-3);
                segmento(x0,fx0,x1,fx1);
            } 
        }
        else{
            for(int i=0; i<100; i++){
                x0 = min + i*(max-min)/100;
                fx0 = (x0*x0+x0-13.0)/(x0-3);
                x1 = min + (i+1)*(max-min)/100;
                fx1 = (x1*x1+x1-13.0)/(x1-3);
                segmento(x0,fx0,x1,fx1);
            }
        }
        

    }//GEN-LAST:event_jButtonRacActionPerformed

    private void jButtonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpActionPerformed
        double min, max, x0, x1, fx0, fx1;
        try{
         min = Integer.parseInt(a.getText());
         max = Integer.parseInt(b.getText());   
        }
        catch(RuntimeException ex){
           JOptionPane.showMessageDialog(this,
                   "INTRODUCIR EL INTERVALO [a,b]",
                   "ERROR", JOptionPane.ERROR_MESSAGE);
           return;
        } 
        
        for(int i=0; i<100; i++){
                x0 = min + i*(max-min)/100;
                fx0 = Math.exp(-x0);
                x1 = min + (i+1)*(max-min)/100;
                fx1 = Math.exp(-x1);
                segmento(x0,fx0,x1,fx1);
            }
    }//GEN-LAST:event_jButtonExpActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        double min, max, x0, x1, fx0, fx1;
        try{
         min = Integer.parseInt(a.getText());
         max = Integer.parseInt(b.getText());   
        }
        catch(RuntimeException ex){
           JOptionPane.showMessageDialog(this,
                   "INTRODUCIR EL INTERVALO [a,b]",
                   "ERROR", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        for(
                int i=0; i<100; i++){
                x0 = 0.0001 + i*(max-0.0001)/100;
                fx0 = Math.log(x0);
                x1 = 0.0001 + (i+1)*(max-0.0001)/100;
                fx1 = Math.log(x1);
                segmento(x0,fx0,x1,fx1);
            }
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonTrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrigActionPerformed
        double min, max, x0, x1, fx0, fx1;
        try{
         min = Integer.parseInt(a.getText());
         max = Integer.parseInt(b.getText());   
        }
        catch(RuntimeException ex){
           JOptionPane.showMessageDialog(this,
                   "INTRODUCIR EL INTERVALO [a,b]",
                   "ERROR", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        if(max<min){
            max = min;
            min = Integer.parseInt(b.getText());
        } 
        
        for(
                int i=0; i<100; i++){
                x0 = min+ i*(max-min)/100;
                fx0 = Math.abs(Math.sin(x0));
                x1 = min + (i+1)*(max-min)/100;
                fx1 = Math.abs(Math.sin(x1));
                segmento(x0,fx0,x1,fx1);
            }
    }//GEN-LAST:event_jButtonTrigActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Escala;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonExp;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonPoli;
    private javax.swing.JButton jButtonRac;
    private javax.swing.JButton jButtonTrig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
